spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/co_tourism
    username: qualitypaper
    password: kolbasa84
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
rsa:
  public-key: classpath:key/public.pem
  private-key: classpath:key/private.pem

confirmation:
  url: http://localhost:8080/api/v1/confirm
forgot-password:
  url: http://localhost:8080/api/v1/forgot-password
